server:
  port: 8762
spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: demo-eureka-client-provider
eureka:
  instance:
    #每隔这个时间会主动心跳一次，默认值为30s
    lease-renewal-interval-in-seconds: 5
    #设置服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，一般是lease-renewal-interval-in-seconds的3倍。
    lease-expiration-duration-in-seconds: 10
  #在eureka server管理页面中点击本服务的 Instance ID的跳转地址，默认为/info
  #      status-page-url: http://${eureka.hostname}:${server.port}/provider
  client:
    healthcheck:
      enabled: true
    service-url:
      #Eureka Server单点
      defaultZone: http://fish119:123456@localhost:8751/eureka/
      #Eureka Server集群
#      defaultZone: http://fish119:123456@peer1:8751/eureka/,http://fish119:123456@peer2:8752/eureka/,http://fish119:123456@peer3:8753/eureka/