server:
  port: 8206

spring:
  main:
    banner-mode: off
    log-startup-info: false
    allow-bean-definition-overriding: true
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos地址
        server-addr: http://localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        security: WARN
#        web: ERROR
#      hibernate: WARN
#      apache:
#        commons:
#          dbcp2: WARN