server:
  port: 8308
spring:
  main:
    banner-mode: off
    log-startup-info: false
    allow-bean-definition-overriding: true
  application:
    name: consul-ribbon-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

service-url:
  consul-user-service: http://consul-user-service

logging:
  level:
    root: WARN
    org:
      springframework:
        security: WARN
        web: ERROR
      hibernate: WARN
      apache:
        commons:
          dbcp2: WARN
