server:
  port: 8771

spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: admin-client
  boot:
    admin:
      client:
        # 配置admin-server地址
        url: http://localhost:8770

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 添加开启admin的日志监控
logging:
  file:
    name: admin-client.log

eureka:
  instance:
    #每隔这个时间会主动心跳一次，默认值为30s
    lease-renewal-interval-in-seconds: 5
    #设置服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，一般是lease-renewal-interval-in-seconds的3倍。
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      #Eureka Server单点
      defaultZone: http://fish119:123456@localhost:8751/eureka/
      #Eureka Server集群
#        defaultZone: http://fish119:123456@peer1:8751/eureka/,http://fish119:123456@peer2:8752/eureka/,http://fish119:123456@peer3:8753/eureka/
