server:
  port: 8767
spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置存储配置信息的Git仓库
          uri: https://gitee.com/vvfish119/springcloud-config.git
          username: vvfish119
          password: fish119
          # 开启启动时直接从git获取配置
          clone-on-start: true
          # 获取子目录下的配置
          search-paths: '{application}'
  security:
    user:
      # 配置用户名和密码
      name: root
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    #每隔这个时间会主动心跳一次，默认值为30s
    lease-renewal-interval-in-seconds: 5
    #设置服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，一般是lease-renewal-interval-in-seconds的3倍。
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    service-url:
      #Eureka Server单点
      defaultZone: http://fish119:123456@localhost:8751/eureka/
      #Eureka Server集群
#        defaultZone: http://fish119:123456@peer1:8751/eureka/,http://fish119:123456@peer2:8752/eureka/,http://fish119:123456@peer3:8753/eureka/

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh